# Simple workflow for deploying static content to GitHub Pages
name: Deploy static of alooooha.com

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "staticPages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: 天翼云静态页面
      url: https://www.alooooha.com
    runs-on: ubuntu-latest
    env: # 在这里定义环境变量
      USER_NAME: alooooha
      IP: 60.188.247.209
      SSH_PRIVATE_KEY: ${{ secrets.tianyiyunKey }} // 私匙

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.IP }} >> ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install dependencies
        run: npm install

      - name: Verify Hexo installation
        run: |
          npx hexo --version

      - name: Check project structure
        run: |
          ls -la

      - name: Build static site
        run: |
          npx hexo generate --cwd .

      - name: Check public directory
        run: |
          ls -la ./public

      - name: 部署到天翼云
        run: |
          scp -r ./public/* ${{ env.USER_NAME }}@${{ env.IP }}:/www/wwwroot/alooooha.com
